name = "Balls"
author = ""
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab8c7253a4b92f77ff9f4758ba868acc495421ecde42c6cc37b520cbfa6f35a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
