name = "Balls"
author = ""
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58972720ef69aaa78256c2007521f55c0068a8ccb3d3f8a7cd9ea4cd274da7b8"

[versions]
minecraft = "1.21.1"
neoforge = ""
